### ISSUE TITLE
Key, Second Highlight

### ISSUE THREAD

**Issue by mahirpiyarali** [mahirpiyarali/LaunchPad-D1#3]
Hey! I had 2 ideas. One, I added in a key after the introduction, do you think this is the best place to put it?

Additionally, I was thinking about adding a second highlight. It would be effective in both the commuting criteria: we could highlight the cities that are in the top 10 worst congestion in N. America and we could highlight the cities that don't have airports? What do you think @thomaswilburn

**Comment by thomaswilburn** [comment]
Both of those sound good to me. I don't think you need to say that some cities will be behind the text--people will get it.

**Comment by mahirpiyarali** [comment]
Question(s) about adding in the highlights:
In the seed.less, I added in the style I want for the red highlight, but I can't figure out where in the main.js to add in the code to incorporate the second highlight. Where do I do that?

Also, I'm wondering about the effectiveness of making the icons "bigger" if they're highlighted.  I'm trying to add in an if statement, but don't know where to put it. @thomaswilburn

**Comment by thomaswilburn** [comment]
Changing the highlight would be a three step process:

1. Add a field to the specified item in story.txt, like `highlight: negative`
2. Pass that through to the section block as a data attribute, same as we do with the filter.
3. Before running the foreach over matched items, first get the value of that attribute. If there is no value, use "highlight" as normal. Then set the class with that, instead of always using a constant "highlight."
